### PR TITLE
fix: add 'parcel' as alternative package name

### PR DESCRIPTION
**Pull request by pReya**
`parcel-bundler` is not the official package name anymore. Currently this means it will not work with projects, that just use `parcel` package. See also: https://github.com/parcel-bundler/parcel/issues/2937

### CODE REVIEW

**Comment by garthenweb** [comment]
Thank you for this! Unfortunately, the changes would cause a breaking change for those who are still using `parcel-bundler`. Do you think there is a way to support both package names at the same time?

**Comment by pReya** [comment]
I changed the old package `parcel-bundler` to be an alias for the new `parcel`. Unfortunately this also means that the package will be installed twice. But this is my best idea to handle backwards compatibility.

**Comment by garthenweb** [comment]
As the dev dependencies will not be installed when installed as a module, I don't think this is going to work. Or do I miss something here?

What do you think about wrapping `require('parcel-bundler/src/assets/CSSAsset')` into try/catch and in case it throws falling back to `require('parcel/src/assets/CSSAsset')`?

Can we also add a test for this?

**Comment by pReya** [comment]
@garthenweb I added the check to see which package exists in the code. However I'm still unsure how to handle the `package.json`. Should we keep both `parcel-bundler` and `parcel` as a devDependency or as a peerDependency? Should we keep the alias for `parcel-bundler`?

**Comment by pReya** [comment]
Any thoughts on this @garthenweb ?

**Comment by garthenweb** [comment]
Looks nice! I would suggest to not update the package.json: we should not install both, a link is also not really what we want here.
The parcel-bundler package has still more downloads and therefore I would like to take that as the default, also because it is used already.
Users usinb parcel will receive a warning as the peer dependency is not matches, but it will still work.
For support of parcel v2 we need to rebuild this plugin anyhow, ai would then also migrate to the new/ official package name!
Anyhow, could we add a test that makes sure this works with the parcel bundle installed?

**Comment by pReya** [comment]
@garthenweb Can you review again? Added a primitive test and moved the whole require logic to a separate function & file.

**Comment by garthenweb** [comment]
Looks good, thank you :)

**Comment by garthenweb** [comment]
@pReya This is now published on npm in version 1.2.0

**Pull request merged**
